image: gitpod/workspace-full

tasks:
  - name: Start ERPNext
    init: |
      git config --global --add safe.directory /workspace/erpnext_docker_setup
      docker compose up -d
    command: sleep infinity

ports:
  - port: 8000
    onOpen: open-preview

